[versions]
## Android
agp-version = "8.6.1"
## Testing
junit-version = "4.13.2"
assertj-version = "3.11.1"
truth = "1.1.5"
mockito-version = "5.10.0"
mockito-kotlin-version = "2.2.0"
powermock-version = "2.0.9"
robolectric-version = "4.11.1"
espresso-version = "3.6.1"
androidx-test-version = "1.7.0"
androidx-rules-version = "1.7.0"
sonarqube-version = "5.1.0.4882"
## Kotlin
kotlin-version = "2.1.10"
kotlinx-coroutines-version = "1.8.0"
kotlinx-serialization-json-version = "1.9.0"
## AndroidX
appcompat-version = "1.6.1"
cardview-version = "1.0.0"
constraintlayout-version = "2.2.1"
work-version = "2.10.0"
lifecycle-version = "2.8.2"
activity-version = "1.9.0"
fragment-version = "1.8.0"
## Google
google-services-version = "4.4.0"
google-firebase-crashlytics-version = "2.9.9"
google-firebase-perf-version = "1.4.2"
google-play-services-version = "21.3.0"
play-services-maps-version = "19.1.0"
play-services-auth-version = "21.3.0"
android-maps-utils-version = "0.5"
material-version = "1.12.0"
## Firebase
firebase-core-version = "21.1.1"
firebase-database-version = "21.0.0"
firebase-auth-version = "23.2.0"
firebase-perf-version = "21.0.4"
firebase-crashlytics-version = "19.4.1"
## DB
realm-android-library-version = "10.17.0"
realm-android-plugin-version = "1.12.1"
## Network
gson-version = "2.10.1"
retrofit-version = "2.9.0"
## Reactive
rxjava3-version = "3.1.5"
rxandroid3-version = "3.0.2"
rxkotlin3-version = "3.0.1"
## UI
glide-version = "4.16.0"
circleimageview-version = "3.1.0"
## Misc
eventbus-version = "3.3.1"
timber-version = "5.0.1"
## DI
hilt-version = "2.55"
## Code quality
jacoco-version = "0.8.13"



[libraries]
## Testing
junit = { group = "junit", name = "junit", version.ref = "junit-version" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj-version" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-version" }
mockito-kotlin = { group = "com.nhaarman.mockitokotlin2", name = "mockito-kotlin", version.ref = "mockito-kotlin-version" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-version" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso-version" }
espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso-version" }
espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso-version" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-version" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-rules-version" }
## Kotlin
kotlin-stdlibjdk = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-version" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-version" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json-version" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines-version" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "kotlinx-coroutines-version" }
## AndroidX
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat-version" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview-version" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout-version" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-version" }
work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "work-version" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-version" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-version" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-version" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-version" }
## Google
google-play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "google-play-services-version" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps-version" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth-version" }
android-maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "android-maps-utils-version" }
material = { module = "com.google.android.material:material", version.ref = "material-version" }
## Firebase
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebase-core-version" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebase-database-version" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth-version" }
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebase-perf-version" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics-version" }
## DB
realm-android-library = { module = "io.realm:realm-android-library", version.ref = "realm-android-library-version" }
## Network
gson = { module = "com.google.code.gson:gson", version.ref = "gson-version" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-version" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit-version" }
## Reactive
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava3-version" }
rxandroid3 = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid3-version" }
rxkotlin3 = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rxkotlin3-version" }
## UI
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide-version" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview-version" }
## Misc
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus-version" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber-version" }
## DI
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-version" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-version" }
## Code quality
jacoco-core = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco-version" }
## Buildscript classpath libraries
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp-version" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
google-services-classpath = { module = "com.google.gms:google-services", version.ref = "google-services-version" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "google-firebase-crashlytics-version" }
firebase-perf-plugin = { module = "com.google.firebase:perf-plugin", version.ref = "google-firebase-perf-version" }
realm-gradle-plugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realm-android-library-version" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt-version" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp-version" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinx-serialization-json-version" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-version" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "google-firebase-crashlytics-version" }
google-firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "google-firebase-perf-version" }
realm-android = { id = "realm-android", version.ref = "realm-android-plugin-version" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube-version" }



[bundles]
local-unit-test = [
    "junit",
    "assertj-core",
    "truth",
    "mockito-core",
    "mockito-kotlin",
    "robolectric"
]
android-ui-test = [
    "espresso-core",
    "espresso-contrib",
    "espresso-intents",
    "androidx-test-runner",
    "androidx-test-rules",
    "espresso-idling-resource"
]
