// coverage.gradle.kts

apply(plugin = "jacoco")

configure<JacocoPluginExtension> {
    toolVersion = "0.8.5"
}

tasks.withType<Test> {
    extensions.configure<JacocoTaskExtension> {
        isIncludeNoLocationClasses = true
        excludes = listOf("jdk.internal.*")
    }
}

val jacocoTestReport = tasks.register<JacocoReport>("jacocoTestReport") {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }

    val fileFilter = listOf(
        "**/R.class",
        "**/R$*.class",
        "**/BuildConfig.*",
        "**/Manifest*.*",
        "**/*\$ViewInjector*.*",
        "**/*\$ViewBinder*.*",
        "**/*\$Lambda\$*.*", // Jacoco can not handle several "$" in class name.
        "**/*Module.*", // Modules for Dagger.
        "**/*Dagger*.*", // Dagger auto-generated code.
        "**/*MembersInjector*.*", // Dagger auto-generated code.
        "**/*_Provide*Factory*.*",
        "**/*_Factory.*", // Dagger auto-generated code
        "**/*\$*\$*.*", // Anonymous classes generated by kotlin
        //add libraries
        "android/**/*.*",
        "uk/**/*.*",
        "io/**/*.*",
        //remove what we don't test
        "androidTest/**/*.*",
        "test/**/*.*",
        "**/injector/**/*.*",
        "**/model/**/*.*",
        "**/mock/**/*.*",
        "**/event/**/*.*",
        "**/**_ViewBinding**",
        "**/*EventType.*",
        "**/**Mocked"
    )

    // TODO: Update dynamic class directory for Java classes
    val debugTree = fileTree(mapOf("dir" to "${buildDir}/intermediates/javac/debug/classes", "excludes" to fileFilter))
    val kotlinDebugTree = fileTree(mapOf("dir" to "${buildDir}/tmp/kotlin-classes/debug", "excludes" to fileFilter))
    val mainSrc = "${project.projectDir}/src/main/java"

    sourceDirectories.setFrom(files(mainSrc))
    classDirectories.setFrom(files(debugTree, kotlinDebugTree))
    executionData.setFrom(
        fileTree(
            mapOf(
                "dir" to "$buildDir",
                "includes" to listOf(
                    "jacoco/testDebugUnitTest.exec",
                    "outputs/code-coverage/connected/*coverage.ec"
                )
            )
        )
    )
}

tasks.register("testProdUnitTest") {
    finalizedBy(jacocoTestReport)
}