apply(plugin = "jacoco")

configure<JacocoPluginExtension> {
    toolVersion = "0.8.12"
}

tasks.withType<Test> {
    extensions.configure<JacocoTaskExtension> {
        isIncludeNoLocationClasses = true
        excludes = listOf("jdk.internal.*")
    }
}

val jacocoTestReport = tasks.register<JacocoReport>("jacocoTestReport") {
    // description
    group = "Reporting"
    description = "Generate JaCoCo coverage reports"

    // ensure tests run before report
    dependsOn("testProdReleaseUnitTest")

    // configure report output formats
    reports {
        // generate XML report for CI/CD
        xml.required.set(true)
        // generate HTML report for local inspection
        html.required.set(true)
    }

    val buildFolder = layout.buildDirectory.get()

    // source directories
    // for mapping coverage to source code
    val mainSrcFolder = files("${project.projectDir}/src/main/java")
    sourceDirectories.setFrom(files(mainSrcFolder))

    // class directories
    val fileFilter = listOf(
        // Android
        "**/R.class",
        "**/R$*.class",
        "**/R\$*.class",
        "**/BuildConfig.*",
        "**/Manifest*.*",
        "**/*Activity.*",
        "**/*Fragment.*",
        "**/*Dialog.*",
        "**/*Service.*",
        // Kotlin
        "**/*\$*\$*.*", // Anonymous classes generated by kotlin
        "**/*Companion*.*", // Companion object
        // Generated
        "**/*\$ViewInjector*.*",
        "**/*\$ViewBinder*.*",
        "**/*\$Lambda\$*.*", // Jacoco can not handle several "$" in class name.
        "**/*Module.*", // Modules for Dagger.
        "**/*Dagger*.*", // Dagger auto-generated code.
        "**/*Hilt*.*", // Hilt auto-generated code.
        "**/*MembersInjector*.*", // Dagger auto-generated code.
        "**/*_Provide*Factory*.*",
        "**/*_Factory.*", // Dagger auto-generated code
        "**/*_Impl*.*",
        "com/iceteaviet/fastfoodfinder/databinding/**/*.*", // ex: ActivityMainBinding
        "**/**_ViewBinding**",
        // libraries
        "android/**/*.*",
        "androidx/**/*.*",
        "com/google/**/*.*",
        "uk/**/*.*",
        "io/**/*.*",
        // unit test generated code
        "androidTest/**/*.*",
        "test/**/*.*",
        "**/injector/**/*.*",
        "**/mock/**/*.*",
        "**/**Mocked",
        // remove our code that don't need unit test
        "com/iceteaviet/fastfoodfinder/App.kt",
        "com/iceteaviet/fastfoodfinder/Injection.kt",
        "com/iceteaviet/fastfoodfinder/ui/base/**/*.*",
        "com/iceteaviet/fastfoodfinder/ui/custom/**/*.*",
    )
    val debugTree = fileTree(
        mapOf(
            "dir" to "${buildFolder}/intermediates/javac/debug/classes",
            "excludes" to fileFilter
        )
    )
    val kotlinDebugTree = fileTree(
        mapOf(
            "dir" to "${buildFolder}/tmp/kotlin-classes/debug",
            "excludes" to fileFilter
        )
    )
    val prodTree = fileTree(
        mapOf(
            "dir" to "${buildFolder}/intermediates/javac/prodRelease/compileProdReleaseJavaWithJavac/classes",
            "excludes" to fileFilter
        )
    )
    val kotlinProdTree = fileTree(
        mapOf(
            "dir" to "${buildFolder}/tmp/kotlin-classes/prodRelease",
            "excludes" to fileFilter
        )
    )
    // use the main classes JAR from the test classpath
    val mainClassesJar = file("${buildFolder}/intermediates/runtime_app_classes_jar/prodRelease/bundleProdReleaseClassesToRuntimeJar/classes.jar")
    classDirectories.setFrom(
        project.zipTree(mainClassesJar).matching {
            exclude(*fileFilter.toTypedArray())
        }
    )

    // execution data
    // from the test task
    val execDataTree = fileTree(
        mapOf(
            "dir" to "$buildFolder/jacoco",
            "includes" to listOf("*.exec")
        )
    )
    executionData.setFrom(execDataTree)

    // logging
    doLast {
        val execDataFolder = buildFolder.dir("jacoco").asFile
        val execDataFiles = execDataFolder.listFiles()?.joinToString(", ") { it.name } ?: "No files found"
        val testReportFolder = buildFolder.dir("reports/jacoco/jacocoTestReport").asFile
        val testReportFiles = testReportFolder.listFiles()?.joinToString(", ") { it.name } ?: "No files found"

        println("")
        println("Jacoco test report generated")
        //println("- Classes: $debugTree, $kotlinDebugTree, $prodTree, $kotlinProdTree")
        println("- Exec data: ${execDataFolder.path} [$execDataFiles]")
        println("- Report: ${testReportFolder.path} [$testReportFiles]")
        println("")
    }
}

tasks.register("testProdUnitTest") {
    finalizedBy(jacocoTestReport)
}